global using System.Diagnostics.CodeAnalysis;
global using CommunityToolkit.Diagnostics;
global using McMaster.Extensions.CommandLineUtils;
global using Microsoft.Extensions.DependencyInjection;
global using TemplateFramework.Console.Commands;
global using TemplateFramework.Console.Contracts;
global using TemplateFramework.Console.Extensions;
global using TemplateFramework.Core;
global using TemplateFramework.Core.Extensions;
