global using System.Reflection;
global using System.Text;
global using FluentAssertions;
global using Moq;
global using TextTemplateTransformationFramework.Abstractions;
global using TextTemplateTransformationFramework.Abstractions.Extensions;
global using TextTemplateTransformationFramework.Abstractions.Infrastructure;
global using TextTemplateTransformationFramework.Core.Contracts;
global using Xunit;
